package com.example.jarchess.online.move;

import com.example.jarchess.match.ChessColor;
import com.example.jarchess.match.Coordinate;
import com.example.jarchess.match.move.Move;
import com.example.jarchess.match.move.PieceMovement;
import com.example.jarchess.match.pieces.PromotionChoice;
import com.example.jarchess.match.turn.Turn;
import com.example.jarchess.online.datapackage.Datapackage;

import org.json.JSONException;
import org.json.JSONObject;
import org.junit.Before;
import org.junit.Test;
import org.junit.experimental.runners.Enclosed;
import org.junit.runner.RunWith;
import org.junit.runners.Parameterized;
import org.junit.runners.Parameterized.Parameter;

import static com.example.jarchess.match.ChessColor.BLACK;
import static com.example.jarchess.match.ChessColor.WHITE;
import static com.example.jarchess.match.pieces.PromotionChoice.PROMOTE_TO_BISHOP;
import static com.example.jarchess.match.pieces.PromotionChoice.PROMOTE_TO_KNIGHT;
import static com.example.jarchess.match.pieces.PromotionChoice.PROMOTE_TO_QUEEN;
import static com.example.jarchess.match.pieces.PromotionChoice.PROMOTE_TO_ROOK;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertSame;

@RunWith(Enclosed.class)
public class DatapackageFormatterTest {

    @RunWith(Parameterized.class)
    public static class SingleMovementTurn {
        /*
         * Test case parameters where partly generated using Joshua Zierman's custom pict utility program
         *
         * This software runs [pict](https://github.com/microsoft/pict) on a model file and uses the results to generate a CSV file and a Java snippet text file.
         *
         * I manually entered the expected string parameters.
         *
         * -Joshua Zierman
         */

        private final static int PARAM_VALUE_ORIGIN_FILE = 0;
        private final static int PARAM_VALUE_ORIGIN_RANK = 1;
        private final static int PARAM_VALUE_DESTINATION_FILE = 2;
        private final static int PARAM_VALUE_DESTINATION_RANK = 3;
        private final static int PARAM_VALUE_TURN_COLOR = 4;
        private final static int PARAM_VALUE_ELAPSED_TIME = 5;
        private final static int PARAM_VALUE_PROMOTION_CHOICE = 6;
        private final static int PARAM_VALUE_EXPECTED_STRING = 7;
        private static final int EXPECTED = 0;
        private static final int ACTUAL = 1;
        @Parameter(value = PARAM_VALUE_ORIGIN_FILE)
        public char originFileParameter;
        @Parameter(value = PARAM_VALUE_ORIGIN_RANK)
        public int originRankParameter;
        @Parameter(value = PARAM_VALUE_DESTINATION_FILE)
        public char destinationFileParameter;
        @Parameter(value = PARAM_VALUE_DESTINATION_RANK)
        public int destinationRankParameter;
        @Parameter(value = PARAM_VALUE_TURN_COLOR)
        public ChessColor turnColorParameter;
        @Parameter(value = PARAM_VALUE_ELAPSED_TIME)
        public long elapsedTimeParameter;
        @Parameter(value = PARAM_VALUE_PROMOTION_CHOICE)
        public PromotionChoice promotionChoiceParameter;
        @Parameter(value = PARAM_VALUE_EXPECTED_STRING)
        public String expectedString;

        private Coordinate[] origin = new Coordinate[2];
        private Coordinate[] destination = new Coordinate[2];
        private ChessColor[] turnColor = new ChessColor[2];
        private long[] elapsedTime = new long[2];
        private String[] ip = new String[2];
        private int[] port = new int[2];
        private PromotionChoice[] chosenPromotion = new PromotionChoice[2];
        private DatapackageFormatter datapackageFormatterUnderTest = new DatapackageFormatter();
        private Datapackage expectedDataPackage;

        @Parameterized.Parameters(name = "{index} | originFile = {" + PARAM_VALUE_ORIGIN_FILE + "}, originRank = {" + PARAM_VALUE_ORIGIN_RANK + "}, destinationFile = {" + PARAM_VALUE_DESTINATION_FILE + "}, destinationRank = {" + PARAM_VALUE_DESTINATION_RANK + "}, turnColor = {" + PARAM_VALUE_TURN_COLOR + "}, elapsedTime = {" + PARAM_VALUE_ELAPSED_TIME + "}, promotionChoice = {" + PARAM_VALUE_PROMOTION_CHOICE + "}")
        public static Object[][] data() {
            return new Object[][]{
                    {/*originFile*/ 'h', /*originRank*/ 6, /*destinationFile*/ 'g', /*destinationRank*/ 2, /*turnColor*/ BLACK, /*elapsedTime*/ 0L, /*promotionChoice*/ PROMOTE_TO_BISHOP, /*expectedString*/"{\"destinationIP\":\"1.2.3.4\",\"destinationPort\":1111,\"turn\":{\"move\":{\"movements\":[{\"origin\":{\"column\":7,\"row\":2},\"destination\":{\"column\":6,\"row\":6}}]},\"color\":{\"intValue\":0,\"name\":\"BLACK\"},\"promotionChoice\":{\"intValue\":2,\"name\":\"PROMOTE_TO_BISHOP\"},\"elapsedTime\":0},\"type\":{\"intValue\":0,\"name\":\"TURN\"}}"},
                    {/*originFile*/ 'b', /*originRank*/ 2, /*destinationFile*/ 'h', /*destinationRank*/ 1, /*turnColor*/ WHITE, /*elapsedTime*/ -1L, /*promotionChoice*/ PROMOTE_TO_QUEEN,/*expectedString*/"{\"destinationIP\":\"1.2.3.4\",\"destinationPort\":1111,\"turn\":{\"move\":{\"movements\":[{\"origin\":{\"column\":1,\"row\":6},\"destination\":{\"column\":7,\"row\":7}}]},\"color\":{\"intValue\":1,\"name\":\"WHITE\"},\"promotionChoice\":{\"intValue\":3,\"name\":\"PROMOTE_TO_QUEEN\"},\"elapsedTime\":-1},\"type\":{\"intValue\":0,\"name\":\"TURN\"}}"},
                    {/*originFile*/ 'c', /*originRank*/ 3, /*destinationFile*/ 'b', /*destinationRank*/ 1, /*turnColor*/ BLACK, /*elapsedTime*/ 1L, /*promotionChoice*/ PROMOTE_TO_KNIGHT,/*expectedString*/"{\"destinationIP\":\"1.2.3.4\",\"destinationPort\":1111,\"turn\":{\"move\":{\"movements\":[{\"origin\":{\"column\":2,\"row\":5},\"destination\":{\"column\":1,\"row\":7}}]},\"color\":{\"intValue\":0,\"name\":\"BLACK\"},\"promotionChoice\":{\"intValue\":1,\"name\":\"PROMOTE_TO_KNIGHT\"},\"elapsedTime\":1},\"type\":{\"intValue\":0,\"name\":\"TURN\"}}"},
                    {/*originFile*/ 'c', /*originRank*/ 5, /*destinationFile*/ 'c', /*destinationRank*/ 2, /*turnColor*/ WHITE, /*elapsedTime*/ Long.MIN_VALUE, /*promotionChoice*/ null,/*expectedString*/"{\"destinationIP\":\"1.2.3.4\",\"destinationPort\":1111,\"turn\":{\"move\":{\"movements\":[{\"origin\":{\"column\":2,\"row\":3},\"destination\":{\"column\":2,\"row\":6}}]},\"color\":{\"intValue\":1,\"name\":\"WHITE\"},\"promotionChoice\":null,\"elapsedTime\":-9223372036854775808},\"type\":{\"intValue\":0,\"name\":\"TURN\"}}"},
                    {/*originFile*/ 'a', /*originRank*/ 2, /*destinationFile*/ 'e', /*destinationRank*/ 3, /*turnColor*/ BLACK, /*elapsedTime*/ Long.MAX_VALUE, /*promotionChoice*/ PROMOTE_TO_ROOK,/*expectedString*/"{\"destinationIP\":\"1.2.3.4\",\"destinationPort\":1111,\"turn\":{\"move\":{\"movements\":[{\"origin\":{\"column\":0,\"row\":6},\"destination\":{\"column\":4,\"row\":5}}]},\"color\":{\"intValue\":0,\"name\":\"BLACK\"},\"promotionChoice\":{\"intValue\":0,\"name\":\"PROMOTE_TO_ROOK\"},\"elapsedTime\":9223372036854775807},\"type\":{\"intValue\":0,\"name\":\"TURN\"}}"},
                    {/*originFile*/ 'a', /*originRank*/ 7, /*destinationFile*/ 'd', /*destinationRank*/ 8, /*turnColor*/ BLACK, /*elapsedTime*/ Long.MIN_VALUE, /*promotionChoice*/ PROMOTE_TO_QUEEN,/*expectedString*/"{\"destinationIP\":\"1.2.3.4\",\"destinationPort\":1111,\"turn\":{\"move\":{\"movements\":[{\"origin\":{\"column\":0,\"row\":1},\"destination\":{\"column\":3,\"row\":0}}]},\"color\":{\"intValue\":0,\"name\":\"BLACK\"},\"promotionChoice\":{\"intValue\":3,\"name\":\"PROMOTE_TO_QUEEN\"},\"elapsedTime\":-9223372036854775808},\"type\":{\"intValue\":0,\"name\":\"TURN\"}}"},
                    {/*originFile*/ 'b', /*originRank*/ 1, /*destinationFile*/ 'b', /*destinationRank*/ 5, /*turnColor*/ WHITE, /*elapsedTime*/ Long.MAX_VALUE, /*promotionChoice*/ PROMOTE_TO_BISHOP,/*expectedString*/"{\"destinationIP\":\"1.2.3.4\",\"destinationPort\":1111,\"turn\":{\"move\":{\"movements\":[{\"origin\":{\"column\":1,\"row\":7},\"destination\":{\"column\":1,\"row\":3}}]},\"color\":{\"intValue\":1,\"name\":\"WHITE\"},\"promotionChoice\":{\"intValue\":2,\"name\":\"PROMOTE_TO_BISHOP\"},\"elapsedTime\":9223372036854775807},\"type\":{\"intValue\":0,\"name\":\"TURN\"}}"},
                    {/*originFile*/ 'f', /*originRank*/ 2, /*destinationFile*/ 'a', /*destinationRank*/ 4, /*turnColor*/ WHITE, /*elapsedTime*/ 0L, /*promotionChoice*/ PROMOTE_TO_KNIGHT,/*expectedString*/"{\"destinationIP\":\"1.2.3.4\",\"destinationPort\":1111,\"turn\":{\"move\":{\"movements\":[{\"origin\":{\"column\":5,\"row\":6},\"destination\":{\"column\":0,\"row\":4}}]},\"color\":{\"intValue\":1,\"name\":\"WHITE\"},\"promotionChoice\":{\"intValue\":1,\"name\":\"PROMOTE_TO_KNIGHT\"},\"elapsedTime\":0},\"type\":{\"intValue\":0,\"name\":\"TURN\"}}"},
                    {/*originFile*/ 'a', /*originRank*/ 4, /*destinationFile*/ 'g', /*destinationRank*/ 6, /*turnColor*/ WHITE, /*elapsedTime*/ 1L, /*promotionChoice*/ null,/*expectedString*/"{\"destinationIP\":\"1.2.3.4\",\"destinationPort\":1111,\"turn\":{\"move\":{\"movements\":[{\"origin\":{\"column\":0,\"row\":4},\"destination\":{\"column\":6,\"row\":2}}]},\"color\":{\"intValue\":1,\"name\":\"WHITE\"},\"promotionChoice\":null,\"elapsedTime\":1},\"type\":{\"intValue\":0,\"name\":\"TURN\"}}"},
                    {/*originFile*/ 'e', /*originRank*/ 8, /*destinationFile*/ 'c', /*destinationRank*/ 8, /*turnColor*/ BLACK, /*elapsedTime*/ -1L, /*promotionChoice*/ PROMOTE_TO_ROOK,/*expectedString*/"{\"destinationIP\":\"1.2.3.4\",\"destinationPort\":1111,\"turn\":{\"move\":{\"movements\":[{\"origin\":{\"column\":4,\"row\":0},\"destination\":{\"column\":2,\"row\":0}}]},\"color\":{\"intValue\":0,\"name\":\"BLACK\"},\"promotionChoice\":{\"intValue\":0,\"name\":\"PROMOTE_TO_ROOK\"},\"elapsedTime\":-1},\"type\":{\"intValue\":0,\"name\":\"TURN\"}}"},
                    {/*originFile*/ 'g', /*originRank*/ 4, /*destinationFile*/ 'd', /*destinationRank*/ 4, /*turnColor*/ BLACK, /*elapsedTime*/ Long.MAX_VALUE, /*promotionChoice*/ null,/*expectedString*/"{\"destinationIP\":\"1.2.3.4\",\"destinationPort\":1111,\"turn\":{\"move\":{\"movements\":[{\"origin\":{\"column\":6,\"row\":4},\"destination\":{\"column\":3,\"row\":4}}]},\"color\":{\"intValue\":0,\"name\":\"BLACK\"},\"promotionChoice\":null,\"elapsedTime\":9223372036854775807},\"type\":{\"intValue\":0,\"name\":\"TURN\"}}"},
                    {/*originFile*/ 'g', /*originRank*/ 6, /*destinationFile*/ 'f', /*destinationRank*/ 3, /*turnColor*/ WHITE, /*elapsedTime*/ 1L, /*promotionChoice*/ PROMOTE_TO_QUEEN,/*expectedString*/"{\"destinationIP\":\"1.2.3.4\",\"destinationPort\":1111,\"turn\":{\"move\":{\"movements\":[{\"origin\":{\"column\":6,\"row\":2},\"destination\":{\"column\":5,\"row\":5}}]},\"color\":{\"intValue\":1,\"name\":\"WHITE\"},\"promotionChoice\":{\"intValue\":3,\"name\":\"PROMOTE_TO_QUEEN\"},\"elapsedTime\":1},\"type\":{\"intValue\":0,\"name\":\"TURN\"}}"},
                    {/*originFile*/ 'e', /*originRank*/ 6, /*destinationFile*/ 'e', /*destinationRank*/ 7, /*turnColor*/ WHITE, /*elapsedTime*/ Long.MIN_VALUE, /*promotionChoice*/ PROMOTE_TO_KNIGHT,/*expectedString*/"{\"destinationIP\":\"1.2.3.4\",\"destinationPort\":1111,\"turn\":{\"move\":{\"movements\":[{\"origin\":{\"column\":4,\"row\":2},\"destination\":{\"column\":4,\"row\":1}}]},\"color\":{\"intValue\":1,\"name\":\"WHITE\"},\"promotionChoice\":{\"intValue\":1,\"name\":\"PROMOTE_TO_KNIGHT\"},\"elapsedTime\":-9223372036854775808},\"type\":{\"intValue\":0,\"name\":\"TURN\"}}"},
                    {/*originFile*/ 'f', /*originRank*/ 1, /*destinationFile*/ 'b', /*destinationRank*/ 6, /*turnColor*/ BLACK, /*elapsedTime*/ Long.MIN_VALUE, /*promotionChoice*/ PROMOTE_TO_ROOK,/*expectedString*/"{\"destinationIP\":\"1.2.3.4\",\"destinationPort\":1111,\"turn\":{\"move\":{\"movements\":[{\"origin\":{\"column\":5,\"row\":7},\"destination\":{\"column\":1,\"row\":2}}]},\"color\":{\"intValue\":0,\"name\":\"BLACK\"},\"promotionChoice\":{\"intValue\":0,\"name\":\"PROMOTE_TO_ROOK\"},\"elapsedTime\":-9223372036854775808},\"type\":{\"intValue\":0,\"name\":\"TURN\"}}"},
                    {/*originFile*/ 'd', /*originRank*/ 2, /*destinationFile*/ 'c', /*destinationRank*/ 7, /*turnColor*/ BLACK, /*elapsedTime*/ 1L, /*promotionChoice*/ PROMOTE_TO_BISHOP,/*expectedString*/"{\"destinationIP\":\"1.2.3.4\",\"destinationPort\":1111,\"turn\":{\"move\":{\"movements\":[{\"origin\":{\"column\":3,\"row\":6},\"destination\":{\"column\":2,\"row\":1}}]},\"color\":{\"intValue\":0,\"name\":\"BLACK\"},\"promotionChoice\":{\"intValue\":2,\"name\":\"PROMOTE_TO_BISHOP\"},\"elapsedTime\":1},\"type\":{\"intValue\":0,\"name\":\"TURN\"}}"},
                    {/*originFile*/ 'd', /*originRank*/ 4, /*destinationFile*/ 'h', /*destinationRank*/ 5, /*turnColor*/ WHITE, /*elapsedTime*/ 0L, /*promotionChoice*/ PROMOTE_TO_ROOK,/*expectedString*/"{\"destinationIP\":\"1.2.3.4\",\"destinationPort\":1111,\"turn\":{\"move\":{\"movements\":[{\"origin\":{\"column\":3,\"row\":4},\"destination\":{\"column\":7,\"row\":3}}]},\"color\":{\"intValue\":1,\"name\":\"WHITE\"},\"promotionChoice\":{\"intValue\":0,\"name\":\"PROMOTE_TO_ROOK\"},\"elapsedTime\":0},\"type\":{\"intValue\":0,\"name\":\"TURN\"}}"},
                    {/*originFile*/ 'h', /*originRank*/ 8, /*destinationFile*/ 'g', /*destinationRank*/ 7, /*turnColor*/ WHITE, /*elapsedTime*/ Long.MAX_VALUE, /*promotionChoice*/ PROMOTE_TO_QUEEN,/*expectedString*/"{\"destinationIP\":\"1.2.3.4\",\"destinationPort\":1111,\"turn\":{\"move\":{\"movements\":[{\"origin\":{\"column\":7,\"row\":0},\"destination\":{\"column\":6,\"row\":1}}]},\"color\":{\"intValue\":1,\"name\":\"WHITE\"},\"promotionChoice\":{\"intValue\":3,\"name\":\"PROMOTE_TO_QUEEN\"},\"elapsedTime\":9223372036854775807},\"type\":{\"intValue\":0,\"name\":\"TURN\"}}"},
                    {/*originFile*/ 'g', /*originRank*/ 5, /*destinationFile*/ 'a', /*destinationRank*/ 5, /*turnColor*/ BLACK, /*elapsedTime*/ -1L, /*promotionChoice*/ PROMOTE_TO_BISHOP,/*expectedString*/"{\"destinationIP\":\"1.2.3.4\",\"destinationPort\":1111,\"turn\":{\"move\":{\"movements\":[{\"origin\":{\"column\":6,\"row\":3},\"destination\":{\"column\":0,\"row\":3}}]},\"color\":{\"intValue\":0,\"name\":\"BLACK\"},\"promotionChoice\":{\"intValue\":2,\"name\":\"PROMOTE_TO_BISHOP\"},\"elapsedTime\":-1},\"type\":{\"intValue\":0,\"name\":\"TURN\"}}"},
                    {/*originFile*/ 'e', /*originRank*/ 3, /*destinationFile*/ 'd', /*destinationRank*/ 3, /*turnColor*/ WHITE, /*elapsedTime*/ 0L, /*promotionChoice*/ PROMOTE_TO_BISHOP,/*expectedString*/"{\"destinationIP\":\"1.2.3.4\",\"destinationPort\":1111,\"turn\":{\"move\":{\"movements\":[{\"origin\":{\"column\":4,\"row\":5},\"destination\":{\"column\":3,\"row\":5}}]},\"color\":{\"intValue\":1,\"name\":\"WHITE\"},\"promotionChoice\":{\"intValue\":2,\"name\":\"PROMOTE_TO_BISHOP\"},\"elapsedTime\":0},\"type\":{\"intValue\":0,\"name\":\"TURN\"}}"},
                    {/*originFile*/ 'a', /*originRank*/ 7, /*destinationFile*/ 'b', /*destinationRank*/ 7, /*turnColor*/ WHITE, /*elapsedTime*/ -1L, /*promotionChoice*/ null,/*expectedString*/"{\"destinationIP\":\"1.2.3.4\",\"destinationPort\":1111,\"turn\":{\"move\":{\"movements\":[{\"origin\":{\"column\":0,\"row\":1},\"destination\":{\"column\":1,\"row\":1}}]},\"color\":{\"intValue\":1,\"name\":\"WHITE\"},\"promotionChoice\":null,\"elapsedTime\":-1},\"type\":{\"intValue\":0,\"name\":\"TURN\"}}"},
                    {/*originFile*/ 'g', /*originRank*/ 8, /*destinationFile*/ 'h', /*destinationRank*/ 6, /*turnColor*/ BLACK, /*elapsedTime*/ Long.MIN_VALUE, /*promotionChoice*/ PROMOTE_TO_KNIGHT,/*expectedString*/"{\"destinationIP\":\"1.2.3.4\",\"destinationPort\":1111,\"turn\":{\"move\":{\"movements\":[{\"origin\":{\"column\":6,\"row\":0},\"destination\":{\"column\":7,\"row\":2}}]},\"color\":{\"intValue\":0,\"name\":\"BLACK\"},\"promotionChoice\":{\"intValue\":1,\"name\":\"PROMOTE_TO_KNIGHT\"},\"elapsedTime\":-9223372036854775808},\"type\":{\"intValue\":0,\"name\":\"TURN\"}}"},
                    {/*originFile*/ 'd', /*originRank*/ 6, /*destinationFile*/ 'b', /*destinationRank*/ 8, /*turnColor*/ WHITE, /*elapsedTime*/ 0L, /*promotionChoice*/ null,/*expectedString*/"{\"destinationIP\":\"1.2.3.4\",\"destinationPort\":1111,\"turn\":{\"move\":{\"movements\":[{\"origin\":{\"column\":3,\"row\":2},\"destination\":{\"column\":1,\"row\":0}}]},\"color\":{\"intValue\":1,\"name\":\"WHITE\"},\"promotionChoice\":null,\"elapsedTime\":0},\"type\":{\"intValue\":0,\"name\":\"TURN\"}}"},
                    {/*originFile*/ 'd', /*originRank*/ 1, /*destinationFile*/ 'd', /*destinationRank*/ 2, /*turnColor*/ BLACK, /*elapsedTime*/ -1L, /*promotionChoice*/ PROMOTE_TO_KNIGHT,/*expectedString*/"{\"destinationIP\":\"1.2.3.4\",\"destinationPort\":1111,\"turn\":{\"move\":{\"movements\":[{\"origin\":{\"column\":3,\"row\":7},\"destination\":{\"column\":3,\"row\":6}}]},\"color\":{\"intValue\":0,\"name\":\"BLACK\"},\"promotionChoice\":{\"intValue\":1,\"name\":\"PROMOTE_TO_KNIGHT\"},\"elapsedTime\":-1},\"type\":{\"intValue\":0,\"name\":\"TURN\"}}"},
                    {/*originFile*/ 'b', /*originRank*/ 1, /*destinationFile*/ 'f', /*destinationRank*/ 1, /*turnColor*/ BLACK, /*elapsedTime*/ 0L, /*promotionChoice*/ null,/*expectedString*/"{\"destinationIP\":\"1.2.3.4\",\"destinationPort\":1111,\"turn\":{\"move\":{\"movements\":[{\"origin\":{\"column\":1,\"row\":7},\"destination\":{\"column\":5,\"row\":7}}]},\"color\":{\"intValue\":0,\"name\":\"BLACK\"},\"promotionChoice\":null,\"elapsedTime\":0},\"type\":{\"intValue\":0,\"name\":\"TURN\"}}"},
                    {/*originFile*/ 'b', /*originRank*/ 3, /*destinationFile*/ 'a', /*destinationRank*/ 4, /*turnColor*/ BLACK, /*elapsedTime*/ 1L, /*promotionChoice*/ PROMOTE_TO_ROOK,/*expectedString*/"{\"destinationIP\":\"1.2.3.4\",\"destinationPort\":1111,\"turn\":{\"move\":{\"movements\":[{\"origin\":{\"column\":1,\"row\":5},\"destination\":{\"column\":0,\"row\":4}}]},\"color\":{\"intValue\":0,\"name\":\"BLACK\"},\"promotionChoice\":{\"intValue\":0,\"name\":\"PROMOTE_TO_ROOK\"},\"elapsedTime\":1},\"type\":{\"intValue\":0,\"name\":\"TURN\"}}"},
                    {/*originFile*/ 'c', /*originRank*/ 1, /*destinationFile*/ 'e', /*destinationRank*/ 4, /*turnColor*/ WHITE, /*elapsedTime*/ 0L, /*promotionChoice*/ PROMOTE_TO_QUEEN,/*expectedString*/"{\"destinationIP\":\"1.2.3.4\",\"destinationPort\":1111,\"turn\":{\"move\":{\"movements\":[{\"origin\":{\"column\":2,\"row\":7},\"destination\":{\"column\":4,\"row\":4}}]},\"color\":{\"intValue\":1,\"name\":\"WHITE\"},\"promotionChoice\":{\"intValue\":3,\"name\":\"PROMOTE_TO_QUEEN\"},\"elapsedTime\":0},\"type\":{\"intValue\":0,\"name\":\"TURN\"}}"},
                    {/*originFile*/ 'b', /*originRank*/ 8, /*destinationFile*/ 'e', /*destinationRank*/ 1, /*turnColor*/ BLACK, /*elapsedTime*/ Long.MIN_VALUE, /*promotionChoice*/ PROMOTE_TO_BISHOP,/*expectedString*/"{\"destinationIP\":\"1.2.3.4\",\"destinationPort\":1111,\"turn\":{\"move\":{\"movements\":[{\"origin\":{\"column\":1,\"row\":0},\"destination\":{\"column\":4,\"row\":7}}]},\"color\":{\"intValue\":0,\"name\":\"BLACK\"},\"promotionChoice\":{\"intValue\":2,\"name\":\"PROMOTE_TO_BISHOP\"},\"elapsedTime\":-9223372036854775808},\"type\":{\"intValue\":0,\"name\":\"TURN\"}}"},
                    {/*originFile*/ 'g', /*originRank*/ 2, /*destinationFile*/ 'f', /*destinationRank*/ 2, /*turnColor*/ BLACK, /*elapsedTime*/ Long.MIN_VALUE, /*promotionChoice*/ PROMOTE_TO_ROOK,/*expectedString*/"{\"destinationIP\":\"1.2.3.4\",\"destinationPort\":1111,\"turn\":{\"move\":{\"movements\":[{\"origin\":{\"column\":6,\"row\":6},\"destination\":{\"column\":5,\"row\":6}}]},\"color\":{\"intValue\":0,\"name\":\"BLACK\"},\"promotionChoice\":{\"intValue\":0,\"name\":\"PROMOTE_TO_ROOK\"},\"elapsedTime\":-9223372036854775808},\"type\":{\"intValue\":0,\"name\":\"TURN\"}}"},
                    {/*originFile*/ 'e', /*originRank*/ 7, /*destinationFile*/ 'a', /*destinationRank*/ 2, /*turnColor*/ WHITE, /*elapsedTime*/ Long.MAX_VALUE, /*promotionChoice*/ PROMOTE_TO_QUEEN,/*expectedString*/"{\"destinationIP\":\"1.2.3.4\",\"destinationPort\":1111,\"turn\":{\"move\":{\"movements\":[{\"origin\":{\"column\":4,\"row\":1},\"destination\":{\"column\":0,\"row\":6}}]},\"color\":{\"intValue\":1,\"name\":\"WHITE\"},\"promotionChoice\":{\"intValue\":3,\"name\":\"PROMOTE_TO_QUEEN\"},\"elapsedTime\":9223372036854775807},\"type\":{\"intValue\":0,\"name\":\"TURN\"}}"},
                    {/*originFile*/ 'h', /*originRank*/ 5, /*destinationFile*/ 'd', /*destinationRank*/ 1, /*turnColor*/ WHITE, /*elapsedTime*/ 1L, /*promotionChoice*/ PROMOTE_TO_ROOK,/*expectedString*/"{\"destinationIP\":\"1.2.3.4\",\"destinationPort\":1111,\"turn\":{\"move\":{\"movements\":[{\"origin\":{\"column\":7,\"row\":3},\"destination\":{\"column\":3,\"row\":7}}]},\"color\":{\"intValue\":1,\"name\":\"WHITE\"},\"promotionChoice\":{\"intValue\":0,\"name\":\"PROMOTE_TO_ROOK\"},\"elapsedTime\":1},\"type\":{\"intValue\":0,\"name\":\"TURN\"}}"},
                    {/*originFile*/ 'd', /*originRank*/ 3, /*destinationFile*/ 'e', /*destinationRank*/ 6, /*turnColor*/ WHITE, /*elapsedTime*/ Long.MAX_VALUE, /*promotionChoice*/ PROMOTE_TO_QUEEN,/*expectedString*/"{\"destinationIP\":\"1.2.3.4\",\"destinationPort\":1111,\"turn\":{\"move\":{\"movements\":[{\"origin\":{\"column\":3,\"row\":5},\"destination\":{\"column\":4,\"row\":2}}]},\"color\":{\"intValue\":1,\"name\":\"WHITE\"},\"promotionChoice\":{\"intValue\":3,\"name\":\"PROMOTE_TO_QUEEN\"},\"elapsedTime\":9223372036854775807},\"type\":{\"intValue\":0,\"name\":\"TURN\"}}"},
                    {/*originFile*/ 'a', /*originRank*/ 5, /*destinationFile*/ 'f', /*destinationRank*/ 5, /*turnColor*/ BLACK, /*elapsedTime*/ Long.MAX_VALUE, /*promotionChoice*/ PROMOTE_TO_KNIGHT,/*expectedString*/"{\"destinationIP\":\"1.2.3.4\",\"destinationPort\":1111,\"turn\":{\"move\":{\"movements\":[{\"origin\":{\"column\":0,\"row\":3},\"destination\":{\"column\":5,\"row\":3}}]},\"color\":{\"intValue\":0,\"name\":\"BLACK\"},\"promotionChoice\":{\"intValue\":1,\"name\":\"PROMOTE_TO_KNIGHT\"},\"elapsedTime\":9223372036854775807},\"type\":{\"intValue\":0,\"name\":\"TURN\"}}"},
                    {/*originFile*/ 'e', /*originRank*/ 5, /*destinationFile*/ 'h', /*destinationRank*/ 4, /*turnColor*/ BLACK, /*elapsedTime*/ -1L, /*promotionChoice*/ null,/*expectedString*/"{\"destinationIP\":\"1.2.3.4\",\"destinationPort\":1111,\"turn\":{\"move\":{\"movements\":[{\"origin\":{\"column\":4,\"row\":3},\"destination\":{\"column\":7,\"row\":4}}]},\"color\":{\"intValue\":0,\"name\":\"BLACK\"},\"promotionChoice\":null,\"elapsedTime\":-1},\"type\":{\"intValue\":0,\"name\":\"TURN\"}}"},
                    {/*originFile*/ 'h', /*originRank*/ 2, /*destinationFile*/ 'e', /*destinationRank*/ 3, /*turnColor*/ BLACK, /*elapsedTime*/ -1L, /*promotionChoice*/ null,/*expectedString*/"{\"destinationIP\":\"1.2.3.4\",\"destinationPort\":1111,\"turn\":{\"move\":{\"movements\":[{\"origin\":{\"column\":7,\"row\":6},\"destination\":{\"column\":4,\"row\":5}}]},\"color\":{\"intValue\":0,\"name\":\"BLACK\"},\"promotionChoice\":null,\"elapsedTime\":-1},\"type\":{\"intValue\":0,\"name\":\"TURN\"}}"},
                    {/*originFile*/ 'e', /*originRank*/ 8, /*destinationFile*/ 'b', /*destinationRank*/ 5, /*turnColor*/ BLACK, /*elapsedTime*/ 1L, /*promotionChoice*/ PROMOTE_TO_QUEEN,/*expectedString*/"{\"destinationIP\":\"1.2.3.4\",\"destinationPort\":1111,\"turn\":{\"move\":{\"movements\":[{\"origin\":{\"column\":4,\"row\":0},\"destination\":{\"column\":1,\"row\":3}}]},\"color\":{\"intValue\":0,\"name\":\"BLACK\"},\"promotionChoice\":{\"intValue\":3,\"name\":\"PROMOTE_TO_QUEEN\"},\"elapsedTime\":1},\"type\":{\"intValue\":0,\"name\":\"TURN\"}}"},
                    {/*originFile*/ 'g', /*originRank*/ 7, /*destinationFile*/ 'c', /*destinationRank*/ 6, /*turnColor*/ WHITE, /*elapsedTime*/ 0L, /*promotionChoice*/ PROMOTE_TO_BISHOP,/*expectedString*/"{\"destinationIP\":\"1.2.3.4\",\"destinationPort\":1111,\"turn\":{\"move\":{\"movements\":[{\"origin\":{\"column\":6,\"row\":1},\"destination\":{\"column\":2,\"row\":2}}]},\"color\":{\"intValue\":1,\"name\":\"WHITE\"},\"promotionChoice\":{\"intValue\":2,\"name\":\"PROMOTE_TO_BISHOP\"},\"elapsedTime\":0},\"type\":{\"intValue\":0,\"name\":\"TURN\"}}"},
                    {/*originFile*/ 'c', /*originRank*/ 4, /*destinationFile*/ 'h', /*destinationRank*/ 8, /*turnColor*/ WHITE, /*elapsedTime*/ Long.MAX_VALUE, /*promotionChoice*/ PROMOTE_TO_BISHOP,/*expectedString*/"{\"destinationIP\":\"1.2.3.4\",\"destinationPort\":1111,\"turn\":{\"move\":{\"movements\":[{\"origin\":{\"column\":2,\"row\":4},\"destination\":{\"column\":7,\"row\":0}}]},\"color\":{\"intValue\":1,\"name\":\"WHITE\"},\"promotionChoice\":{\"intValue\":2,\"name\":\"PROMOTE_TO_BISHOP\"},\"elapsedTime\":9223372036854775807},\"type\":{\"intValue\":0,\"name\":\"TURN\"}}"},
                    {/*originFile*/ 'b', /*originRank*/ 5, /*destinationFile*/ 'g', /*destinationRank*/ 7, /*turnColor*/ WHITE, /*elapsedTime*/ 0L, /*promotionChoice*/ PROMOTE_TO_KNIGHT,/*expectedString*/"{\"destinationIP\":\"1.2.3.4\",\"destinationPort\":1111,\"turn\":{\"move\":{\"movements\":[{\"origin\":{\"column\":1,\"row\":3},\"destination\":{\"column\":6,\"row\":1}}]},\"color\":{\"intValue\":1,\"name\":\"WHITE\"},\"promotionChoice\":{\"intValue\":1,\"name\":\"PROMOTE_TO_KNIGHT\"},\"elapsedTime\":0},\"type\":{\"intValue\":0,\"name\":\"TURN\"}}"},
                    {/*originFile*/ 'f', /*originRank*/ 7, /*destinationFile*/ 'g', /*destinationRank*/ 1, /*turnColor*/ BLACK, /*elapsedTime*/ -1L, /*promotionChoice*/ PROMOTE_TO_ROOK,/*expectedString*/"{\"destinationIP\":\"1.2.3.4\",\"destinationPort\":1111,\"turn\":{\"move\":{\"movements\":[{\"origin\":{\"column\":5,\"row\":1},\"destination\":{\"column\":6,\"row\":7}}]},\"color\":{\"intValue\":0,\"name\":\"BLACK\"},\"promotionChoice\":{\"intValue\":0,\"name\":\"PROMOTE_TO_ROOK\"},\"elapsedTime\":-1},\"type\":{\"intValue\":0,\"name\":\"TURN\"}}"},
                    {/*originFile*/ 'f', /*originRank*/ 3, /*destinationFile*/ 'e', /*destinationRank*/ 5, /*turnColor*/ BLACK, /*elapsedTime*/ Long.MIN_VALUE, /*promotionChoice*/ null,/*expectedString*/"{\"destinationIP\":\"1.2.3.4\",\"destinationPort\":1111,\"turn\":{\"move\":{\"movements\":[{\"origin\":{\"column\":5,\"row\":5},\"destination\":{\"column\":4,\"row\":3}}]},\"color\":{\"intValue\":0,\"name\":\"BLACK\"},\"promotionChoice\":null,\"elapsedTime\":-9223372036854775808},\"type\":{\"intValue\":0,\"name\":\"TURN\"}}"},
                    {/*originFile*/ 'f', /*originRank*/ 7, /*destinationFile*/ 'h', /*destinationRank*/ 3, /*turnColor*/ BLACK, /*elapsedTime*/ 1L, /*promotionChoice*/ PROMOTE_TO_KNIGHT,/*expectedString*/"{\"destinationIP\":\"1.2.3.4\",\"destinationPort\":1111,\"turn\":{\"move\":{\"movements\":[{\"origin\":{\"column\":5,\"row\":1},\"destination\":{\"column\":7,\"row\":5}}]},\"color\":{\"intValue\":0,\"name\":\"BLACK\"},\"promotionChoice\":{\"intValue\":1,\"name\":\"PROMOTE_TO_KNIGHT\"},\"elapsedTime\":1},\"type\":{\"intValue\":0,\"name\":\"TURN\"}}"},
                    {/*originFile*/ 'e', /*originRank*/ 2, /*destinationFile*/ 'g', /*destinationRank*/ 4, /*turnColor*/ BLACK, /*elapsedTime*/ Long.MIN_VALUE, /*promotionChoice*/ PROMOTE_TO_BISHOP,/*expectedString*/"{\"destinationIP\":\"1.2.3.4\",\"destinationPort\":1111,\"turn\":{\"move\":{\"movements\":[{\"origin\":{\"column\":4,\"row\":6},\"destination\":{\"column\":6,\"row\":4}}]},\"color\":{\"intValue\":0,\"name\":\"BLACK\"},\"promotionChoice\":{\"intValue\":2,\"name\":\"PROMOTE_TO_BISHOP\"},\"elapsedTime\":-9223372036854775808},\"type\":{\"intValue\":0,\"name\":\"TURN\"}}"},
                    {/*originFile*/ 'a', /*originRank*/ 1, /*destinationFile*/ 'a', /*destinationRank*/ 8, /*turnColor*/ BLACK, /*elapsedTime*/ 1L, /*promotionChoice*/ PROMOTE_TO_BISHOP,/*expectedString*/"{\"destinationIP\":\"1.2.3.4\",\"destinationPort\":1111,\"turn\":{\"move\":{\"movements\":[{\"origin\":{\"column\":0,\"row\":7},\"destination\":{\"column\":0,\"row\":0}}]},\"color\":{\"intValue\":0,\"name\":\"BLACK\"},\"promotionChoice\":{\"intValue\":2,\"name\":\"PROMOTE_TO_BISHOP\"},\"elapsedTime\":1},\"type\":{\"intValue\":0,\"name\":\"TURN\"}}"},
                    {/*originFile*/ 'f', /*originRank*/ 6, /*destinationFile*/ 'c', /*destinationRank*/ 8, /*turnColor*/ WHITE, /*elapsedTime*/ Long.MAX_VALUE, /*promotionChoice*/ PROMOTE_TO_QUEEN,/*expectedString*/"{\"destinationIP\":\"1.2.3.4\",\"destinationPort\":1111,\"turn\":{\"move\":{\"movements\":[{\"origin\":{\"column\":5,\"row\":2},\"destination\":{\"column\":2,\"row\":0}}]},\"color\":{\"intValue\":1,\"name\":\"WHITE\"},\"promotionChoice\":{\"intValue\":3,\"name\":\"PROMOTE_TO_QUEEN\"},\"elapsedTime\":9223372036854775807},\"type\":{\"intValue\":0,\"name\":\"TURN\"}}"},
                    {/*originFile*/ 'c', /*originRank*/ 6, /*destinationFile*/ 'f', /*destinationRank*/ 3, /*turnColor*/ WHITE, /*elapsedTime*/ -1L, /*promotionChoice*/ PROMOTE_TO_ROOK,/*expectedString*/"{\"destinationIP\":\"1.2.3.4\",\"destinationPort\":1111,\"turn\":{\"move\":{\"movements\":[{\"origin\":{\"column\":2,\"row\":2},\"destination\":{\"column\":5,\"row\":5}}]},\"color\":{\"intValue\":1,\"name\":\"WHITE\"},\"promotionChoice\":{\"intValue\":0,\"name\":\"PROMOTE_TO_ROOK\"},\"elapsedTime\":-1},\"type\":{\"intValue\":0,\"name\":\"TURN\"}}"},
                    {/*originFile*/ 'h', /*originRank*/ 4, /*destinationFile*/ 'c', /*destinationRank*/ 1, /*turnColor*/ BLACK, /*elapsedTime*/ Long.MAX_VALUE, /*promotionChoice*/ PROMOTE_TO_KNIGHT,/*expectedString*/"{\"destinationIP\":\"1.2.3.4\",\"destinationPort\":1111,\"turn\":{\"move\":{\"movements\":[{\"origin\":{\"column\":7,\"row\":4},\"destination\":{\"column\":2,\"row\":7}}]},\"color\":{\"intValue\":0,\"name\":\"BLACK\"},\"promotionChoice\":{\"intValue\":1,\"name\":\"PROMOTE_TO_KNIGHT\"},\"elapsedTime\":9223372036854775807},\"type\":{\"intValue\":0,\"name\":\"TURN\"}}"},
                    {/*originFile*/ 'f', /*originRank*/ 4, /*destinationFile*/ 'e', /*destinationRank*/ 2, /*turnColor*/ BLACK, /*elapsedTime*/ 1L, /*promotionChoice*/ PROMOTE_TO_QUEEN,/*expectedString*/"{\"destinationIP\":\"1.2.3.4\",\"destinationPort\":1111,\"turn\":{\"move\":{\"movements\":[{\"origin\":{\"column\":5,\"row\":4},\"destination\":{\"column\":4,\"row\":6}}]},\"color\":{\"intValue\":0,\"name\":\"BLACK\"},\"promotionChoice\":{\"intValue\":3,\"name\":\"PROMOTE_TO_QUEEN\"},\"elapsedTime\":1},\"type\":{\"intValue\":0,\"name\":\"TURN\"}}"},
                    {/*originFile*/ 'c', /*originRank*/ 6, /*destinationFile*/ 'd', /*destinationRank*/ 5, /*turnColor*/ WHITE, /*elapsedTime*/ Long.MIN_VALUE, /*promotionChoice*/ PROMOTE_TO_QUEEN,/*expectedString*/"{\"destinationIP\":\"1.2.3.4\",\"destinationPort\":1111,\"turn\":{\"move\":{\"movements\":[{\"origin\":{\"column\":2,\"row\":2},\"destination\":{\"column\":3,\"row\":3}}]},\"color\":{\"intValue\":1,\"name\":\"WHITE\"},\"promotionChoice\":{\"intValue\":3,\"name\":\"PROMOTE_TO_QUEEN\"},\"elapsedTime\":-9223372036854775808},\"type\":{\"intValue\":0,\"name\":\"TURN\"}}"},
                    {/*originFile*/ 'h', /*originRank*/ 8, /*destinationFile*/ 'a', /*destinationRank*/ 4, /*turnColor*/ BLACK, /*elapsedTime*/ Long.MIN_VALUE, /*promotionChoice*/ null,/*expectedString*/"{\"destinationIP\":\"1.2.3.4\",\"destinationPort\":1111,\"turn\":{\"move\":{\"movements\":[{\"origin\":{\"column\":7,\"row\":0},\"destination\":{\"column\":0,\"row\":4}}]},\"color\":{\"intValue\":0,\"name\":\"BLACK\"},\"promotionChoice\":null,\"elapsedTime\":-9223372036854775808},\"type\":{\"intValue\":0,\"name\":\"TURN\"}}"},
                    {/*originFile*/ 'f', /*originRank*/ 8, /*destinationFile*/ 'd', /*destinationRank*/ 7, /*turnColor*/ BLACK, /*elapsedTime*/ 0L, /*promotionChoice*/ PROMOTE_TO_ROOK,/*expectedString*/"{\"destinationIP\":\"1.2.3.4\",\"destinationPort\":1111,\"turn\":{\"move\":{\"movements\":[{\"origin\":{\"column\":5,\"row\":0},\"destination\":{\"column\":3,\"row\":1}}]},\"color\":{\"intValue\":0,\"name\":\"BLACK\"},\"promotionChoice\":{\"intValue\":0,\"name\":\"PROMOTE_TO_ROOK\"},\"elapsedTime\":0},\"type\":{\"intValue\":0,\"name\":\"TURN\"}}"},
                    {/*originFile*/ 'd', /*originRank*/ 7, /*destinationFile*/ 'f', /*destinationRank*/ 4, /*turnColor*/ BLACK, /*elapsedTime*/ Long.MIN_VALUE, /*promotionChoice*/ PROMOTE_TO_BISHOP,/*expectedString*/"{\"destinationIP\":\"1.2.3.4\",\"destinationPort\":1111,\"turn\":{\"move\":{\"movements\":[{\"origin\":{\"column\":3,\"row\":1},\"destination\":{\"column\":5,\"row\":4}}]},\"color\":{\"intValue\":0,\"name\":\"BLACK\"},\"promotionChoice\":{\"intValue\":2,\"name\":\"PROMOTE_TO_BISHOP\"},\"elapsedTime\":-9223372036854775808},\"type\":{\"intValue\":0,\"name\":\"TURN\"}}"},
                    {/*originFile*/ 'e', /*originRank*/ 4, /*destinationFile*/ 'b', /*destinationRank*/ 4, /*turnColor*/ WHITE, /*elapsedTime*/ -1L, /*promotionChoice*/ PROMOTE_TO_BISHOP,/*expectedString*/"{\"destinationIP\":\"1.2.3.4\",\"destinationPort\":1111,\"turn\":{\"move\":{\"movements\":[{\"origin\":{\"column\":4,\"row\":4},\"destination\":{\"column\":1,\"row\":4}}]},\"color\":{\"intValue\":1,\"name\":\"WHITE\"},\"promotionChoice\":{\"intValue\":2,\"name\":\"PROMOTE_TO_BISHOP\"},\"elapsedTime\":-1},\"type\":{\"intValue\":0,\"name\":\"TURN\"}}"},
                    {/*originFile*/ 'a', /*originRank*/ 6, /*destinationFile*/ 'a', /*destinationRank*/ 1, /*turnColor*/ BLACK, /*elapsedTime*/ 0L, /*promotionChoice*/ PROMOTE_TO_BISHOP,/*expectedString*/"{\"destinationIP\":\"1.2.3.4\",\"destinationPort\":1111,\"turn\":{\"move\":{\"movements\":[{\"origin\":{\"column\":0,\"row\":2},\"destination\":{\"column\":0,\"row\":7}}]},\"color\":{\"intValue\":0,\"name\":\"BLACK\"},\"promotionChoice\":{\"intValue\":2,\"name\":\"PROMOTE_TO_BISHOP\"},\"elapsedTime\":0},\"type\":{\"intValue\":0,\"name\":\"TURN\"}}"},
                    {/*originFile*/ 'd', /*originRank*/ 4, /*destinationFile*/ 'a', /*destinationRank*/ 3, /*turnColor*/ BLACK, /*elapsedTime*/ Long.MIN_VALUE, /*promotionChoice*/ PROMOTE_TO_BISHOP,/*expectedString*/"{\"destinationIP\":\"1.2.3.4\",\"destinationPort\":1111,\"turn\":{\"move\":{\"movements\":[{\"origin\":{\"column\":3,\"row\":4},\"destination\":{\"column\":0,\"row\":5}}]},\"color\":{\"intValue\":0,\"name\":\"BLACK\"},\"promotionChoice\":{\"intValue\":2,\"name\":\"PROMOTE_TO_BISHOP\"},\"elapsedTime\":-9223372036854775808},\"type\":{\"intValue\":0,\"name\":\"TURN\"}}"},
                    {/*originFile*/ 'f', /*originRank*/ 5, /*destinationFile*/ 'f', /*destinationRank*/ 6, /*turnColor*/ BLACK, /*elapsedTime*/ -1L, /*promotionChoice*/ PROMOTE_TO_QUEEN,/*expectedString*/"{\"destinationIP\":\"1.2.3.4\",\"destinationPort\":1111,\"turn\":{\"move\":{\"movements\":[{\"origin\":{\"column\":5,\"row\":3},\"destination\":{\"column\":5,\"row\":2}}]},\"color\":{\"intValue\":0,\"name\":\"BLACK\"},\"promotionChoice\":{\"intValue\":3,\"name\":\"PROMOTE_TO_QUEEN\"},\"elapsedTime\":-1},\"type\":{\"intValue\":0,\"name\":\"TURN\"}}"},
                    {/*originFile*/ 'b', /*originRank*/ 3, /*destinationFile*/ 'f', /*destinationRank*/ 8, /*turnColor*/ WHITE, /*elapsedTime*/ -1L, /*promotionChoice*/ PROMOTE_TO_KNIGHT,/*expectedString*/"{\"destinationIP\":\"1.2.3.4\",\"destinationPort\":1111,\"turn\":{\"move\":{\"movements\":[{\"origin\":{\"column\":1,\"row\":5},\"destination\":{\"column\":5,\"row\":0}}]},\"color\":{\"intValue\":1,\"name\":\"WHITE\"},\"promotionChoice\":{\"intValue\":1,\"name\":\"PROMOTE_TO_KNIGHT\"},\"elapsedTime\":-1},\"type\":{\"intValue\":0,\"name\":\"TURN\"}}"},
                    {/*originFile*/ 'c', /*originRank*/ 2, /*destinationFile*/ 'd', /*destinationRank*/ 6, /*turnColor*/ BLACK, /*elapsedTime*/ Long.MAX_VALUE, /*promotionChoice*/ PROMOTE_TO_BISHOP,/*expectedString*/"{\"destinationIP\":\"1.2.3.4\",\"destinationPort\":1111,\"turn\":{\"move\":{\"movements\":[{\"origin\":{\"column\":2,\"row\":6},\"destination\":{\"column\":3,\"row\":2}}]},\"color\":{\"intValue\":0,\"name\":\"BLACK\"},\"promotionChoice\":{\"intValue\":2,\"name\":\"PROMOTE_TO_BISHOP\"},\"elapsedTime\":9223372036854775807},\"type\":{\"intValue\":0,\"name\":\"TURN\"}}"},
                    {/*originFile*/ 'a', /*originRank*/ 3, /*destinationFile*/ 'h', /*destinationRank*/ 2, /*turnColor*/ BLACK, /*elapsedTime*/ Long.MIN_VALUE, /*promotionChoice*/ PROMOTE_TO_QUEEN,/*expectedString*/"{\"destinationIP\":\"1.2.3.4\",\"destinationPort\":1111,\"turn\":{\"move\":{\"movements\":[{\"origin\":{\"column\":0,\"row\":5},\"destination\":{\"column\":7,\"row\":6}}]},\"color\":{\"intValue\":0,\"name\":\"BLACK\"},\"promotionChoice\":{\"intValue\":3,\"name\":\"PROMOTE_TO_QUEEN\"},\"elapsedTime\":-9223372036854775808},\"type\":{\"intValue\":0,\"name\":\"TURN\"}}"},
                    {/*originFile*/ 'd', /*originRank*/ 8, /*destinationFile*/ 'g', /*destinationRank*/ 3, /*turnColor*/ WHITE, /*elapsedTime*/ Long.MAX_VALUE, /*promotionChoice*/ PROMOTE_TO_KNIGHT,/*expectedString*/"{\"destinationIP\":\"1.2.3.4\",\"destinationPort\":1111,\"turn\":{\"move\":{\"movements\":[{\"origin\":{\"column\":3,\"row\":0},\"destination\":{\"column\":6,\"row\":5}}]},\"color\":{\"intValue\":1,\"name\":\"WHITE\"},\"promotionChoice\":{\"intValue\":1,\"name\":\"PROMOTE_TO_KNIGHT\"},\"elapsedTime\":9223372036854775807},\"type\":{\"intValue\":0,\"name\":\"TURN\"}}"},
                    {/*originFile*/ 'e', /*originRank*/ 1, /*destinationFile*/ 'f', /*destinationRank*/ 6, /*turnColor*/ BLACK, /*elapsedTime*/ -1L, /*promotionChoice*/ PROMOTE_TO_BISHOP,/*expectedString*/"{\"destinationIP\":\"1.2.3.4\",\"destinationPort\":1111,\"turn\":{\"move\":{\"movements\":[{\"origin\":{\"column\":4,\"row\":7},\"destination\":{\"column\":5,\"row\":2}}]},\"color\":{\"intValue\":0,\"name\":\"BLACK\"},\"promotionChoice\":{\"intValue\":2,\"name\":\"PROMOTE_TO_BISHOP\"},\"elapsedTime\":-1},\"type\":{\"intValue\":0,\"name\":\"TURN\"}}"},
                    {/*originFile*/ 'g', /*originRank*/ 5, /*destinationFile*/ 'e', /*destinationRank*/ 8, /*turnColor*/ BLACK, /*elapsedTime*/ Long.MIN_VALUE, /*promotionChoice*/ PROMOTE_TO_ROOK,/*expectedString*/"{\"destinationIP\":\"1.2.3.4\",\"destinationPort\":1111,\"turn\":{\"move\":{\"movements\":[{\"origin\":{\"column\":6,\"row\":3},\"destination\":{\"column\":4,\"row\":0}}]},\"color\":{\"intValue\":0,\"name\":\"BLACK\"},\"promotionChoice\":{\"intValue\":0,\"name\":\"PROMOTE_TO_ROOK\"},\"elapsedTime\":-9223372036854775808},\"type\":{\"intValue\":0,\"name\":\"TURN\"}}"},
                    {/*originFile*/ 'h', /*originRank*/ 7, /*destinationFile*/ 'b', /*destinationRank*/ 5, /*turnColor*/ BLACK, /*elapsedTime*/ 0L, /*promotionChoice*/ PROMOTE_TO_QUEEN,/*expectedString*/"{\"destinationIP\":\"1.2.3.4\",\"destinationPort\":1111,\"turn\":{\"move\":{\"movements\":[{\"origin\":{\"column\":7,\"row\":1},\"destination\":{\"column\":1,\"row\":3}}]},\"color\":{\"intValue\":0,\"name\":\"BLACK\"},\"promotionChoice\":{\"intValue\":3,\"name\":\"PROMOTE_TO_QUEEN\"},\"elapsedTime\":0},\"type\":{\"intValue\":0,\"name\":\"TURN\"}}"},
                    {/*originFile*/ 'b', /*originRank*/ 4, /*destinationFile*/ 'f', /*destinationRank*/ 7, /*turnColor*/ WHITE, /*elapsedTime*/ Long.MAX_VALUE, /*promotionChoice*/ PROMOTE_TO_BISHOP,/*expectedString*/"{\"destinationIP\":\"1.2.3.4\",\"destinationPort\":1111,\"turn\":{\"move\":{\"movements\":[{\"origin\":{\"column\":1,\"row\":4},\"destination\":{\"column\":5,\"row\":1}}]},\"color\":{\"intValue\":1,\"name\":\"WHITE\"},\"promotionChoice\":{\"intValue\":2,\"name\":\"PROMOTE_TO_BISHOP\"},\"elapsedTime\":9223372036854775807},\"type\":{\"intValue\":0,\"name\":\"TURN\"}}"},
                    {/*originFile*/ 'b', /*originRank*/ 8, /*destinationFile*/ 'b', /*destinationRank*/ 2, /*turnColor*/ WHITE, /*elapsedTime*/ 0L, /*promotionChoice*/ PROMOTE_TO_QUEEN,/*expectedString*/"{\"destinationIP\":\"1.2.3.4\",\"destinationPort\":1111,\"turn\":{\"move\":{\"movements\":[{\"origin\":{\"column\":1,\"row\":0},\"destination\":{\"column\":1,\"row\":6}}]},\"color\":{\"intValue\":1,\"name\":\"WHITE\"},\"promotionChoice\":{\"intValue\":3,\"name\":\"PROMOTE_TO_QUEEN\"},\"elapsedTime\":0},\"type\":{\"intValue\":0,\"name\":\"TURN\"}}"},
                    {/*originFile*/ 'd', /*originRank*/ 6, /*destinationFile*/ 'h', /*destinationRank*/ 1, /*turnColor*/ BLACK, /*elapsedTime*/ 1L, /*promotionChoice*/ null,/*expectedString*/"{\"destinationIP\":\"1.2.3.4\",\"destinationPort\":1111,\"turn\":{\"move\":{\"movements\":[{\"origin\":{\"column\":3,\"row\":2},\"destination\":{\"column\":7,\"row\":7}}]},\"color\":{\"intValue\":0,\"name\":\"BLACK\"},\"promotionChoice\":null,\"elapsedTime\":1},\"type\":{\"intValue\":0,\"name\":\"TURN\"}}"},
                    {/*originFile*/ 'h', /*originRank*/ 1, /*destinationFile*/ 'h', /*destinationRank*/ 7, /*turnColor*/ WHITE, /*elapsedTime*/ Long.MAX_VALUE, /*promotionChoice*/ PROMOTE_TO_QUEEN,/*expectedString*/"{\"destinationIP\":\"1.2.3.4\",\"destinationPort\":1111,\"turn\":{\"move\":{\"movements\":[{\"origin\":{\"column\":7,\"row\":7},\"destination\":{\"column\":7,\"row\":1}}]},\"color\":{\"intValue\":1,\"name\":\"WHITE\"},\"promotionChoice\":{\"intValue\":3,\"name\":\"PROMOTE_TO_QUEEN\"},\"elapsedTime\":9223372036854775807},\"type\":{\"intValue\":0,\"name\":\"TURN\"}}"},
                    {/*originFile*/ 'g', /*originRank*/ 3, /*destinationFile*/ 'g', /*destinationRank*/ 1, /*turnColor*/ BLACK, /*elapsedTime*/ Long.MIN_VALUE, /*promotionChoice*/ PROMOTE_TO_QUEEN,/*expectedString*/"{\"destinationIP\":\"1.2.3.4\",\"destinationPort\":1111,\"turn\":{\"move\":{\"movements\":[{\"origin\":{\"column\":6,\"row\":5},\"destination\":{\"column\":6,\"row\":7}}]},\"color\":{\"intValue\":0,\"name\":\"BLACK\"},\"promotionChoice\":{\"intValue\":3,\"name\":\"PROMOTE_TO_QUEEN\"},\"elapsedTime\":-9223372036854775808},\"type\":{\"intValue\":0,\"name\":\"TURN\"}}"},
                    {/*originFile*/ 'h', /*originRank*/ 6, /*destinationFile*/ 'f', /*destinationRank*/ 6, /*turnColor*/ BLACK, /*elapsedTime*/ 1L, /*promotionChoice*/ PROMOTE_TO_KNIGHT,/*expectedString*/"{\"destinationIP\":\"1.2.3.4\",\"destinationPort\":1111,\"turn\":{\"move\":{\"movements\":[{\"origin\":{\"column\":7,\"row\":2},\"destination\":{\"column\":5,\"row\":2}}]},\"color\":{\"intValue\":0,\"name\":\"BLACK\"},\"promotionChoice\":{\"intValue\":1,\"name\":\"PROMOTE_TO_KNIGHT\"},\"elapsedTime\":1},\"type\":{\"intValue\":0,\"name\":\"TURN\"}}"},
                    {/*originFile*/ 'h', /*originRank*/ 3, /*destinationFile*/ 'c', /*destinationRank*/ 7, /*turnColor*/ WHITE, /*elapsedTime*/ 0L, /*promotionChoice*/ PROMOTE_TO_ROOK,/*expectedString*/"{\"destinationIP\":\"1.2.3.4\",\"destinationPort\":1111,\"turn\":{\"move\":{\"movements\":[{\"origin\":{\"column\":7,\"row\":5},\"destination\":{\"column\":2,\"row\":1}}]},\"color\":{\"intValue\":1,\"name\":\"WHITE\"},\"promotionChoice\":{\"intValue\":0,\"name\":\"PROMOTE_TO_ROOK\"},\"elapsedTime\":0},\"type\":{\"intValue\":0,\"name\":\"TURN\"}}"},
                    {/*originFile*/ 'c', /*originRank*/ 7, /*destinationFile*/ 'a', /*destinationRank*/ 7, /*turnColor*/ WHITE, /*elapsedTime*/ 1L, /*promotionChoice*/ PROMOTE_TO_BISHOP,/*expectedString*/"{\"destinationIP\":\"1.2.3.4\",\"destinationPort\":1111,\"turn\":{\"move\":{\"movements\":[{\"origin\":{\"column\":2,\"row\":1},\"destination\":{\"column\":0,\"row\":1}}]},\"color\":{\"intValue\":1,\"name\":\"WHITE\"},\"promotionChoice\":{\"intValue\":2,\"name\":\"PROMOTE_TO_BISHOP\"},\"elapsedTime\":1},\"type\":{\"intValue\":0,\"name\":\"TURN\"}}"},
                    {/*originFile*/ 'g', /*originRank*/ 1, /*destinationFile*/ 'g', /*destinationRank*/ 5, /*turnColor*/ BLACK, /*elapsedTime*/ 0L, /*promotionChoice*/ PROMOTE_TO_BISHOP,/*expectedString*/"{\"destinationIP\":\"1.2.3.4\",\"destinationPort\":1111,\"turn\":{\"move\":{\"movements\":[{\"origin\":{\"column\":6,\"row\":7},\"destination\":{\"column\":6,\"row\":3}}]},\"color\":{\"intValue\":0,\"name\":\"BLACK\"},\"promotionChoice\":{\"intValue\":2,\"name\":\"PROMOTE_TO_BISHOP\"},\"elapsedTime\":0},\"type\":{\"intValue\":0,\"name\":\"TURN\"}}"},
                    {/*originFile*/ 'a', /*originRank*/ 8, /*destinationFile*/ 'c', /*destinationRank*/ 4, /*turnColor*/ WHITE, /*elapsedTime*/ Long.MIN_VALUE, /*promotionChoice*/ PROMOTE_TO_KNIGHT,/*expectedString*/"{\"destinationIP\":\"1.2.3.4\",\"destinationPort\":1111,\"turn\":{\"move\":{\"movements\":[{\"origin\":{\"column\":0,\"row\":0},\"destination\":{\"column\":2,\"row\":4}}]},\"color\":{\"intValue\":1,\"name\":\"WHITE\"},\"promotionChoice\":{\"intValue\":1,\"name\":\"PROMOTE_TO_KNIGHT\"},\"elapsedTime\":-9223372036854775808},\"type\":{\"intValue\":0,\"name\":\"TURN\"}}"},
                    {/*originFile*/ 'e', /*originRank*/ 2, /*destinationFile*/ 'b', /*destinationRank*/ 1, /*turnColor*/ WHITE, /*elapsedTime*/ 0L, /*promotionChoice*/ PROMOTE_TO_BISHOP,/*expectedString*/"{\"destinationIP\":\"1.2.3.4\",\"destinationPort\":1111,\"turn\":{\"move\":{\"movements\":[{\"origin\":{\"column\":4,\"row\":6},\"destination\":{\"column\":1,\"row\":7}}]},\"color\":{\"intValue\":1,\"name\":\"WHITE\"},\"promotionChoice\":{\"intValue\":2,\"name\":\"PROMOTE_TO_BISHOP\"},\"elapsedTime\":0},\"type\":{\"intValue\":0,\"name\":\"TURN\"}}"},
                    {/*originFile*/ 'f', /*originRank*/ 2, /*destinationFile*/ 'c', /*destinationRank*/ 5, /*turnColor*/ BLACK, /*elapsedTime*/ -1L, /*promotionChoice*/ PROMOTE_TO_BISHOP,/*expectedString*/"{\"destinationIP\":\"1.2.3.4\",\"destinationPort\":1111,\"turn\":{\"move\":{\"movements\":[{\"origin\":{\"column\":5,\"row\":6},\"destination\":{\"column\":2,\"row\":3}}]},\"color\":{\"intValue\":0,\"name\":\"BLACK\"},\"promotionChoice\":{\"intValue\":2,\"name\":\"PROMOTE_TO_BISHOP\"},\"elapsedTime\":-1},\"type\":{\"intValue\":0,\"name\":\"TURN\"}}"},
                    {/*originFile*/ 'c', /*originRank*/ 8, /*destinationFile*/ 'f', /*destinationRank*/ 6, /*turnColor*/ BLACK, /*elapsedTime*/ Long.MAX_VALUE, /*promotionChoice*/ PROMOTE_TO_BISHOP,/*expectedString*/"{\"destinationIP\":\"1.2.3.4\",\"destinationPort\":1111,\"turn\":{\"move\":{\"movements\":[{\"origin\":{\"column\":2,\"row\":0},\"destination\":{\"column\":5,\"row\":2}}]},\"color\":{\"intValue\":0,\"name\":\"BLACK\"},\"promotionChoice\":{\"intValue\":2,\"name\":\"PROMOTE_TO_BISHOP\"},\"elapsedTime\":9223372036854775807},\"type\":{\"intValue\":0,\"name\":\"TURN\"}}"},
                    {/*originFile*/ 'g', /*originRank*/ 5, /*destinationFile*/ 'b', /*destinationRank*/ 3, /*turnColor*/ BLACK, /*elapsedTime*/ -1L, /*promotionChoice*/ null,/*expectedString*/"{\"destinationIP\":\"1.2.3.4\",\"destinationPort\":1111,\"turn\":{\"move\":{\"movements\":[{\"origin\":{\"column\":6,\"row\":3},\"destination\":{\"column\":1,\"row\":5}}]},\"color\":{\"intValue\":0,\"name\":\"BLACK\"},\"promotionChoice\":null,\"elapsedTime\":-1},\"type\":{\"intValue\":0,\"name\":\"TURN\"}}"},
                    {/*originFile*/ 'b', /*originRank*/ 1, /*destinationFile*/ 'c', /*destinationRank*/ 3, /*turnColor*/ WHITE, /*elapsedTime*/ 1L, /*promotionChoice*/ PROMOTE_TO_ROOK,/*expectedString*/"{\"destinationIP\":\"1.2.3.4\",\"destinationPort\":1111,\"turn\":{\"move\":{\"movements\":[{\"origin\":{\"column\":1,\"row\":7},\"destination\":{\"column\":2,\"row\":5}}]},\"color\":{\"intValue\":1,\"name\":\"WHITE\"},\"promotionChoice\":{\"intValue\":0,\"name\":\"PROMOTE_TO_ROOK\"},\"elapsedTime\":1},\"type\":{\"intValue\":0,\"name\":\"TURN\"}}"},
                    {/*originFile*/ 'd', /*originRank*/ 5, /*destinationFile*/ 'g', /*destinationRank*/ 8, /*turnColor*/ WHITE, /*elapsedTime*/ Long.MAX_VALUE, /*promotionChoice*/ PROMOTE_TO_KNIGHT,/*expectedString*/"{\"destinationIP\":\"1.2.3.4\",\"destinationPort\":1111,\"turn\":{\"move\":{\"movements\":[{\"origin\":{\"column\":3,\"row\":3},\"destination\":{\"column\":6,\"row\":0}}]},\"color\":{\"intValue\":1,\"name\":\"WHITE\"},\"promotionChoice\":{\"intValue\":1,\"name\":\"PROMOTE_TO_KNIGHT\"},\"elapsedTime\":9223372036854775807},\"type\":{\"intValue\":0,\"name\":\"TURN\"}}"},
                    {/*originFile*/ 'b', /*originRank*/ 7, /*destinationFile*/ 'a', /*destinationRank*/ 6, /*turnColor*/ BLACK, /*elapsedTime*/ -1L, /*promotionChoice*/ PROMOTE_TO_BISHOP,/*expectedString*/"{\"destinationIP\":\"1.2.3.4\",\"destinationPort\":1111,\"turn\":{\"move\":{\"movements\":[{\"origin\":{\"column\":1,\"row\":1},\"destination\":{\"column\":0,\"row\":2}}]},\"color\":{\"intValue\":0,\"name\":\"BLACK\"},\"promotionChoice\":{\"intValue\":2,\"name\":\"PROMOTE_TO_BISHOP\"},\"elapsedTime\":-1},\"type\":{\"intValue\":0,\"name\":\"TURN\"}}"},
                    {/*originFile*/ 'b', /*originRank*/ 6, /*destinationFile*/ 'd', /*destinationRank*/ 4, /*turnColor*/ BLACK, /*elapsedTime*/ 1L, /*promotionChoice*/ PROMOTE_TO_ROOK,/*expectedString*/"{\"destinationIP\":\"1.2.3.4\",\"destinationPort\":1111,\"turn\":{\"move\":{\"movements\":[{\"origin\":{\"column\":1,\"row\":2},\"destination\":{\"column\":3,\"row\":4}}]},\"color\":{\"intValue\":0,\"name\":\"BLACK\"},\"promotionChoice\":{\"intValue\":0,\"name\":\"PROMOTE_TO_ROOK\"},\"elapsedTime\":1},\"type\":{\"intValue\":0,\"name\":\"TURN\"}}"},
                    {/*originFile*/ 'h', /*originRank*/ 2, /*destinationFile*/ 'e', /*destinationRank*/ 8, /*turnColor*/ WHITE, /*elapsedTime*/ Long.MAX_VALUE, /*promotionChoice*/ null,/*expectedString*/"{\"destinationIP\":\"1.2.3.4\",\"destinationPort\":1111,\"turn\":{\"move\":{\"movements\":[{\"origin\":{\"column\":7,\"row\":6},\"destination\":{\"column\":4,\"row\":0}}]},\"color\":{\"intValue\":1,\"name\":\"WHITE\"},\"promotionChoice\":null,\"elapsedTime\":9223372036854775807},\"type\":{\"intValue\":0,\"name\":\"TURN\"}}"},
                    {/*originFile*/ 'g', /*originRank*/ 7, /*destinationFile*/ 'e', /*destinationRank*/ 7, /*turnColor*/ BLACK, /*elapsedTime*/ -1L, /*promotionChoice*/ null,/*expectedString*/"{\"destinationIP\":\"1.2.3.4\",\"destinationPort\":1111,\"turn\":{\"move\":{\"movements\":[{\"origin\":{\"column\":6,\"row\":1},\"destination\":{\"column\":4,\"row\":1}}]},\"color\":{\"intValue\":0,\"name\":\"BLACK\"},\"promotionChoice\":null,\"elapsedTime\":-1},\"type\":{\"intValue\":0,\"name\":\"TURN\"}}"},
                    {/*originFile*/ 'c', /*originRank*/ 1, /*destinationFile*/ 'g', /*destinationRank*/ 7, /*turnColor*/ BLACK, /*elapsedTime*/ -1L, /*promotionChoice*/ PROMOTE_TO_QUEEN,/*expectedString*/"{\"destinationIP\":\"1.2.3.4\",\"destinationPort\":1111,\"turn\":{\"move\":{\"movements\":[{\"origin\":{\"column\":2,\"row\":7},\"destination\":{\"column\":6,\"row\":1}}]},\"color\":{\"intValue\":0,\"name\":\"BLACK\"},\"promotionChoice\":{\"intValue\":3,\"name\":\"PROMOTE_TO_QUEEN\"},\"elapsedTime\":-1},\"type\":{\"intValue\":0,\"name\":\"TURN\"}}"}
            };
        }

        @Test
        public void dataPkgToJson() {
            JSONObject jsonObject = datapackageFormatterUnderTest.dataPkgToJson(expectedDataPackage);


            assertEquals("JSON to string not as expected: ", expectedString, jsonObject.toString());
        }

        @Test
        public void jsonObjToDataPkg() throws JSONException {
            // make the JSONObject from the provided string
            JSONObject jsonObject = new JSONObject(expectedString);

            // use the datapackageFormatter that we are trying to test to convert that JSONObject to a Datapackage
            Datapackage actualDatapackage = datapackageFormatterUnderTest.jsonObjToDataPkg(jsonObject);

            // check that everything is as expected
            Turn resultingTurn = actualDatapackage.getTurn();
            Move resultingMove = resultingTurn.getMove();
            PieceMovement[] resultingMovements = new PieceMovement[0];
            resultingMovements = resultingMove.toArray(resultingMovements);

            assertEquals("resultingMoments.length != 1", 1, resultingMovements.length);

            origin[ACTUAL] = resultingMovements[0].getOrigin();
            destination[ACTUAL] = resultingMovements[0].getDestination();
            turnColor[ACTUAL] = resultingTurn.getColor();
            elapsedTime[ACTUAL] = resultingTurn.getElapsedTime();
            chosenPromotion[ACTUAL] = resultingTurn.getPromotionChoice();
            ip[ACTUAL] = actualDatapackage.getDestinationIP();
            port[ACTUAL] = actualDatapackage.getDestinationPort();
            chosenPromotion[ACTUAL] = resultingTurn.getPromotionChoice();

            assertSame("origins not same.", origin[EXPECTED], origin[ACTUAL]);
            assertSame("destinations not same.", destination[EXPECTED], destination[ACTUAL]);
            assertSame("turn color not same.", turnColor[EXPECTED], turnColor[ACTUAL]);
            assertEquals("elapsed time not same.", elapsedTime[EXPECTED], elapsedTime[ACTUAL]);
            assertSame("chosen promotion is not the same.", chosenPromotion[EXPECTED], chosenPromotion[ACTUAL]);

        }

        @Before
        public void setup() {


            origin[EXPECTED] = Coordinate.getByFileAndRank(originFileParameter, originRankParameter);
            destination[EXPECTED] = Coordinate.getByFileAndRank(destinationFileParameter, destinationRankParameter);
            Move move = new Move(origin[EXPECTED], destination[EXPECTED]);
            ChessColor color = turnColor[EXPECTED] = turnColorParameter;
            long time = elapsedTime[EXPECTED] = elapsedTimeParameter;
            PromotionChoice pieceType = chosenPromotion[EXPECTED] = promotionChoiceParameter;

            //TODO I should parameterize these and test the acceptable bounds.
            ip[EXPECTED] = "1.2.3.4";
            port[EXPECTED] = 1111;


            Turn turnExpected = new Turn(color, move, time, pieceType);

            expectedDataPackage = new Datapackage(turnExpected, ip[EXPECTED], port[EXPECTED]);
        }
    }

    //TODO I should create test for invalid parameters.
}